// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528121510_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entity.ScoreComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ScoreRecordId")
                        .HasColumnType("integer");

                    b.Property<double>("ScoreValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.HasKey("Id");

                    b.HasIndex("ScoreRecordId");

                    b.ToTable("score_components", null, t =>
                        {
                            t.HasCheckConstraint("CK_score_components_score_value_nonneg", "\"ScoreValue\" >= 0");

                            t.HasCheckConstraint("CK_score_components_weight_positive", "\"Weight\" > 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.ScoreRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("FinalGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ImportedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Fail");

                    b.Property<int>("SubjectClassId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RollNumber");

                    b.HasIndex("SubjectClassId");

                    b.ToTable("score_records", null, t =>
                        {
                            t.HasCheckConstraint("CK_score_records_status_allowed", "\"Status\" IN ('Fail', 'Pass')");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entity.SubjectClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("subject_classes", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entity.ScoreComponent", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.ScoreRecord", "ScoreRecord")
                        .WithMany("ScoreComponents")
                        .HasForeignKey("ScoreRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoreRecord");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.ScoreRecord", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.SubjectClass", "SubjectClass")
                        .WithMany("ScoreRecords")
                        .HasForeignKey("SubjectClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubjectClass");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.ScoreRecord", b =>
                {
                    b.Navigation("ScoreComponents");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.SubjectClass", b =>
                {
                    b.Navigation("ScoreRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
